## HW1
Questions from Juliaacademy

One extra question

Getting started

1.1
Look up docs for the convert function.

In [1]:
?convert

search: convert ConcurrencyViolationError code_native @code_native



```
convert(T, x)
```

Convert `x` to a value of type `T`.

If `T` is an [`Integer`](@ref) type, an [`InexactError`](@ref) will be raised if `x` is not representable by `T`, for example if `x` is not integer-valued, or is outside the range supported by `T`.

# Examples

```jldoctest
julia> convert(Int, 3.0)
3

julia> convert(Int, 3.5)
ERROR: InexactError: Int64(3.5)
Stacktrace:
[...]
```

If `T` is a [`AbstractFloat`](@ref) type, then it will return the closest value to `x` representable by `T`.

```jldoctest
julia> x = 1/3
0.3333333333333333

julia> convert(Float32, x)
0.33333334f0

julia> convert(BigFloat, x)
0.333333333333333314829616256247390992939472198486328125
```

If `T` is a collection type and `x` a collection, the result of `convert(T, x)` may alias all or part of `x`.

```jldoctest
julia> x = Int[1, 2, 3];

julia> y = convert(Vector{Int}, x);

julia> y === x
true
```

See also: [`round`](@ref), [`trunc`](@ref), [`oftype`](@ref), [`reinterpret`](@ref).


1.2

Assign 365 to a variable named days. Convert days to a float and assign it to variable days_float

In [ ]:
days=365
days_float=convert(Float64, days)

In [ ]:
@assert days==365
@assert days_float==365.0

1.3
See what happens when you execute

convert(Int64, "1")
and

parse(Int64, "1")

In [ ]:
convert(Int64, "1")

In [ ]:
parse(Int64, "1")

# Strings

2.1

Create a string that says "hi" 1000 times, first with repeat and then with the exponentiation operator, 

which can call * under the hood. Assign it the variable hi below.

In [ ]:
repeat("hi",1000)

In [ ]:
 Hi="hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi
hihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihihi
hihihihihihihihihihihihihihihihihihihihihihihihi"
 Hi=Hi*Hi*Hi*Hi*Hi*Hi*Hi*Hi*Hi*Hi

In [ ]:
@assert hi == Hi

# 2.2
Declare two variables

a = 3
b = 4
and use them to create two strings:

"3 + 4"
"7"
and store the results in c and d respectively

In [ ]:
a=3;
b=4;

In [ ]:
c=string(a , string(+) ,  b)

In [ ]:
d=string(a + b)

In [ ]:
@assert c == "3+4"
@assert d == "7"

# Data stuctures
3.1
Create an array, a_ray, with the following code:

a_ray = [1, 2, 3]
Add the number 4 to the end of this array and then remove it.

In [ ]:
a_ray=[1,2,3]
push!(a_ray, 4)

In [ ]:
pop!(a_ray)

In [ ]:
@assert a_ray == [1, 2, 3]

# 3.2
Try to add "Emergency" as key to myphonebook with the value string(911) with the following code

myphonebook["Emergency"] = 911
Why doesn't this work?

In [ ]:
myphonebook["Emergency"] = 911

In [ ]:
# Why doesn't this work?
# Answer: Because there is no defined dictionary here, where this emergency contact could be added. 
# That is why it is showing this error. It should be like below:
myphonebook=Dict("Emergency"=>"911")

# 3.3
Create a new dictionary called flexible_phonebook that has Jenny's number stored as an integer and Ghostbusters' number stored as a string with the following code

flexible_phonebook = Dict("Jenny" => 8675309, "Ghostbusters" => "555-2368")

In [ ]:
flexible_phonebook = Dict("Jenny" => 8675309, "Ghostbusters" => "555-2368")

In [ ]:
@assert flexible_phonebook == Dict("Jenny" => 8675309, "Ghostbusters" => "555-2368")

# 3.4
Add the key "Emergency" with the value 911 (an integer) to flexible_phonebook.

In [ ]:
flexible_phonebook["Emergency"]=911
flexible_phonebook

In [ ]:
@assert haskey(flexible_phonebook, "Emergency")

In [ ]:
@assert flexible_phonebook["Emergency"] == 911

# 3.5
Why can we add an integer as a value to flexible_phonebook but not myphonebook? 
How could we have initialized myphonebook so that it would accept integers as values? 
(hint: try using Julia's documentation for dictionaries)

In [ ]:
# Answer: Because In first case of myphonebook there is no defined dictionary using 'Dict', 
# where as in flexible_phonebook there is a proper defined dictionary. We can initialized myphonebook as below:
myphonebook=Dict("Emergency"=>911)

# Loops
4.1
Loop over integers between 1 and 100 and print their squares.

In [ ]:
for n = 1:100
    n=n^2
    println(n)
end

# 4.2
Add to the code above a bit to create a dictionary, squares that holds integers and their squares as key, 
value pairs such that squares[10] == 100

In [8]:
squares=Dict()
for n = 1:100
   squares[n]=n^2
end
print(squares)

Dict{Any, Any}(5 => 25, 56 => 3136, 35 => 1225, 55 => 3025, 60 => 3600, 30 => 900, 32 => 1024, 6 => 36, 67 => 4489, 45 => 2025, 73 => 5329, 64 => 4096, 90 => 8100, 4 => 16, 13 => 169, 54 => 2916, 63 => 3969, 86 => 7396, 91 => 8281, 62 => 3844, 58 => 3364, 52 => 2704, 12 => 144, 28 => 784, 75 => 5625, 23 => 529, 92 => 8464, 41 => 1681, 43 => 1849, 11 => 121, 36 => 1296, 68 => 4624, 69 => 4761, 98 => 9604, 82 => 6724, 85 => 7225, 39 => 1521, 84 => 7056, 77 => 5929, 7 => 49, 25 => 625, 95 => 9025, 71 => 5041, 66 => 4356, 76 => 5776, 34 => 1156, 50 => 2500, 59 => 3481, 93 => 8649, 2 => 4, 10 => 100, 18 => 324, 26 => 676, 27 => 729, 42 => 1764, 87 => 7569, 100 => 10000, 79 => 6241, 16 => 256, 20 => 400, 81 => 6561, 19 => 361, 49 => 2401, 44 => 1936, 9 => 81, 31 => 961, 74 => 5476, 61 => 3721, 29 => 841, 94 => 8836, 46 => 2116, 57 => 3249, 70 => 4900, 21 => 441, 38 => 1444, 88 => 7744, 78 => 6084, 72 => 5184, 24 => 576, 8 => 64, 17 => 289, 37 => 1369, 1 => 1, 53 => 2809, 22 => 484, 47 => 220

In [9]:
@assert squares[10] == 100
@assert squares[11] == 121

# 4.3
Use an array comprehension to create an an array squares_arr that stores the squares for all integers between 1 and 100.

In [52]:
squares_arr=[n^2 for n in 1:100]

100-element Vector{Int64}:
     1
     4
     9
    16
    25
    36
    49
    64
    81
   100
   121
   144
   169
     ⋮
  7921
  8100
  8281
  8464
  8649
  8836
  9025
  9216
  9409
  9604
  9801
 10000

In [53]:
@assert length(squares_arr) == 100
 @assert sum(squares_arr) == 338350

# Conditionals
5.1
Write a conditional statement that prints a number if the number is even and the string "odd" if the number is odd.

In [ ]:
x=5
if x%2==0
    println(x)
else
    println("odd")
end

# 5.2
Rewrite the code from 5.1 using a ternary operator.

In [ ]:
(x %2 ==0) ? x : "odd" 

# Functions
6.1
Write a function add_one that adds 1 to its input.

In [ ]:
function add_one(num)
   
    num=num+1 
    
end

In [ ]:
@assert add_one(1) == 2

In [ ]:
@assert add_one(11) == 12

# 6.2
Use map or broadcast to increment every element of matrix A by 1 and assign it to a variable A1.

In [ ]:
A=[1 2 3;4 5 6;7 8 9]

A1=add_one.(A)

In [ ]:
@assert A1 == [2 3 4; 5 6 7; 8 9 10]

# 6.3
Use the broadcast dot syntax to increment every element of matrix A1 by 1 and store it in variable A2

In [ ]:
A2=add_one.(A1)

In [ ]:
@assert A2 == [3 4 5; 6 7 8; 9 10 11]

# Packages
7.1
Load the Primes package (source code at https://github.com/JuliaMath/Primes.jl ).

In [5]:
import Pkg
using Pkg
Pkg.add("Primes")
using Primes

   Resolving package versions...
  No Changes to `C:\Users\Rasel\.julia\environments\v1.8\Project.toml`
  No Changes to `C:\Users\Rasel\.julia\environments\v1.8\Manifest.toml`


In [6]:
@assert @isdefined Primes 

# 7.2
Verify that you can now use the function primes to grab all prime numbers under 1,000,000 and store it in variable primes_list

In [8]:
primes_list=primes(1000000)

78498-element Vector{Int64}:
      2
      3
      5
      7
     11
     13
     17
     19
     23
     29
     31
     37
     41
      ⋮
 999809
 999853
 999863
 999883
 999907
 999917
 999931
 999953
 999959
 999961
 999979
 999983

# Plotting
8.1
Given

x = -10:10

plot y vs. x for y=x^2. You may want to change backends back again.

In [ ]:
import Pkg
Pkg.add("Plots")
Pkg.add("Colors")

In [ ]:
using Plots
using Colors
gr()

In [ ]:
x=-10:10
f(x)=x^2
y=f.(x)
plot(x,y, label="line")
scatter!(x, y, label="points")

# 8.2
Execute the following code

In [ ]:
p1 = plot(x, x)
p2 = plot(x, x.^2)
p3 = plot(x, x.^3)
p4 = plot(x, x.^4)
plot(p1, p2, p3, p4, layout = (2, 2), legend = false)

# Create a (4*1) plot that uses p1, p2, p3, and p4 as subplots.

In [ ]:
plot(p1, p2, p3, p4, layout = (4, 1), legend = false)

# Extra Exercise
Write a function that will output a Fibonacci Sequence with a length of N

Function name: fibonacciN

Input: N::Int32

Output: a N-element vector that stores a Fibonacci Sequence

Example: fibonacciN(50) => [0, 1, …., 7778742049]

In the Fibonacci Sequence, the first two numbers are 0 and 1 and every number thereafter

is the sum of the previous two numbers in the sequence For this question, 

consider 0 to be the 1st Fibonacci Number, not the 0th (i.e. do not zero-index)

In [9]:
function fibonacciN(N::Int)
    F=zeros(N)
    F[1]=0; F[2]=1
   for i=3:N
    F[i]=F[i-1]+F[i-2]
    end
    F
end

fibonacciN (generic function with 2 methods)

In [10]:
fibonacciN(50)

50-element Vector{Float64}:
   0.0
   1.0
   1.0
   2.0
   3.0
   5.0
   8.0
  13.0
  21.0
  34.0
  55.0
  89.0
 144.0
   ⋮
   3.9088169e7
   6.3245986e7
   1.02334155e8
   1.65580141e8
   2.67914296e8
   4.33494437e8
   7.01408733e8
   1.13490317e9
   1.836311903e9
   2.971215073e9
   4.807526976e9
   7.778742049e9